---
# defaults file for configure_bastion

tools_packages:
  - tmux

firewall_service_rules:
  - http
  - https

firewall_port_rules:
  - "6443/tcp"
  - "22643/tcp"

ssh_key_name: "cluster-ocp-key"

# HTTP server

http_server_package_name: "httpd"
http_server_service_name: "httpd"
http_server_user: "apache"
http_server_group: "apache"
http_server_data_dir: "/var/www/html"
http_server_ignition_files_dir_name: "ignition"

# OpenShift install-config vars (should be replaced)

openshift_version: "4.2.7"
openshift_cluster_name: "ocp-cluster"

openshift_base_domain: "example.com"
openshift_worker_replicas_number: "0"
openshift_master_replicas_number: "3"

# vCenter variables
openshift_vcenter:
  host: "your_vcenter_server"
  username: "your_vsphere_username"
  password: "your_vsphere_password"
  datacenter: "your_datacenter"
  cluster: "your_cluster"
  default_datastore: "your_datastore"
  folder: "your_folder"

# general OpenShift vars

openshift_binary_dir: "/usr/bin"
openshift_working_directory_name: "{{ openshift_cluster_name }}"
openshift_working_directory_path: "{{ ansible_env.HOME }}/{{ openshift_working_directory_name }}"
openshift_binaries_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}"

openshift_installer_binary_url: "{{ openshift_binaries_url }}/openshift-install-linux-{{ openshift_version }}.tar.gz"
openshift_installer_binary_name: "openshift-install"
openshift_installer_binary_mode: "0755"
_openshift_installer_cmd: "{{ openshift_binary_dir }}/{{ openshift_installer_binary_name }}"

openshift_oc_client_binary_url: "{{ openshift_binaries_url }}/openshift-client-linux-{{ openshift_version }}.tar.gz"
openshift_oc_client_binary_name: "oc"
openshift_oc_client_binary_mode: "0755"
_openshift_oc_client_cmd: "{{ openshift_binary_dir }}/{{ openshift_oc_client_binary_name }}"

openshift_install_config_yaml_name: "install-config.yaml"

# OpenShift manifests vars
openshift_manifests_dir_name: "manifests"
openshift_cluster_scheduler_manifest:
  filename: "cluster-scheduler-02-config.yml"
  value: "false"

# OpenShift ignition config files vars

openshift_append_bootstrap_ign_name: "append-bootstrap.ign"
openshift_ignition_config_files_root_names:
  - "master"
  - "worker"
  - "append-bootstrap"
